# Generated by Django 3.2.13 on 2022-04-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('security', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('concierge', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('nmbr_of_rooms', models.IntegerField()),
                ('Nmbr_of_pieces', models.IntegerField()),
                ('Nmbr_of_bathrooms', models.IntegerField()),
                ('condition', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
