# Generated by Django 3.2.13 on 2022-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='surface',
            field=models.IntegerField(default=0),
        ),
    ]
