# Generated by Django 3.2.13 on 2022-04-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartements', '0002_appartement_surface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartement',
            old_name='condition',
            new_name='type',
        ),
    ]
